on: [push, pull_request]
name: Test
jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
       make actions-test
       bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  race-unit-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: RACE=1 make test
  memfs-unit-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: MEMFS_TEST=1 make test
  go1-18-unit-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: make test
  macos-unit-test:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: make test
  build-tools:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: make tools
  build-examples:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Build
      run: |
       git clone https://github.com/lni/dragonboat-example
       cd dragonboat-example
       GOPROXY=direct go get github.com/lni/dragonboat/v4@master
       make
  static-check:
    runs-on: ubuntu-22.04
    steps: 
     - name: Install Go
       uses: actions/setup-go@v3
       with:
         go-version: 1.19.x
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Static check
       run: |
        make install-static-check-tools
        make static-check
